# Generated by Django 5.2.7 on 2025-10-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='食品名')),
                ('expiration_date', models.DateField(verbose_name='賞味期限')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='画像URL')),
                ('category', models.CharField(choices=[('refrigerator', '冷蔵庫'), ('pantry', '備蓄庫')], max_length=20, verbose_name='カテゴリ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
        ),
    ]
