# Generated by Django 5.2.7 on 2025-10-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_quantity_food_storage_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='storage_location',
            field=models.CharField(max_length=20, verbose_name='収納場所'),
        ),
    ]
