# Generated by Django 5.2.7 on 2025-10-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_storage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='jan_code',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='JANコード'),
        ),
    ]
