# Generated by Django 5.2.7 on 2025-10-27 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_food_jan_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RakutenProductCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan_code', models.CharField(max_length=13, unique=True, verbose_name='JANコード')),
                ('item_name', models.CharField(max_length=200, verbose_name='商品名')),
                ('Company_name', models.CharField(max_length=40, verbose_name='メーカー名')),
                ('item_price', models.PositiveIntegerField(default=0, verbose_name='価格')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='画像URL')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='取得日時')),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.RemoveField(
            model_name='food',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='food',
            name='expiration_date',
            field=models.DateField(verbose_name='賞味期限'),
        ),
        migrations.CreateModel(
            name='ConsumedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed_at', models.DateTimeField(auto_now_add=True, verbose_name='消費日時')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='消費量')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food', verbose_name='消費された食品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='通知メッセージ')),
                ('notified_at', models.DateTimeField(auto_now_add=True, verbose_name='通知日時')),
                ('type', models.CharField(choices=[('expiry', '賞味期限通知')], max_length=20, verbose_name='通知種別')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food', verbose_name='対象食品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='レシピ名')),
                ('ingredients', models.TextField(verbose_name='材料')),
                ('url', models.URLField(verbose_name='レシピURL')),
                ('suggested_at', models.DateTimeField(auto_now_add=True, verbose_name='提案日時')),
                ('suggested_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food', verbose_name='対象食品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
