# Generated by Django 5.2.7 on 2025-10-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_rakutenproductcache_remove_food_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
