# Generated by Django 5.2.7 on 2025-10-30 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_food_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='notified',
        ),
    ]
