# Generated by Django 5.2.7 on 2025-10-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_remove_food_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='doc_id',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True, unique=True, verbose_name='Firestore用ID'),
        ),
    ]
