# Generated by Django 5.2.7 on 2025-10-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_food_doc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='doc_id',
            field=models.CharField(editable=False, max_length=150, unique=True, verbose_name='Firestore用ID'),
        ),
    ]
