# Generated by Django 5.2.7 on 2025-10-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_alter_food_doc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='maker',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='メーカー名'),
        ),
    ]
